general:
  num_entries: 100
  num_columns: 5
  telling_cred_index_in_table: -1
  credentials_to_include:
    #Example:
    #- "Marko, Morrison, markom, password"
    #(DON'T INCLUDE ENTRY ID)
full_names:

usernames:
  naming_convention:
    first_name_letter_num: -1
    last_name_letter_num: -1
    first_name_placed_first: True
passwords:
  online_mode:
    url: "https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/xato-net-10-million-passwords.txt"
  complexity_requirements:
    minimum_length: -1
    minimum_digits: -1
    minimum_symbols: -1
    minimum_caps: -1