general:
  num_entries: 100
  num_columns: 5
  telling_cred_index_in_table: 4
full_names:

usernames:
  naming_convention:
    first_name_letter_num: -1
    last_name_letter_num: -1
    first_name_placed_first: True
passwords: